spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://210.42.145.77/koalait?serverTimezone=GMT%2B8&userUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: hello
  mvc:
    date-format: yyyy-MM-dd
